// Generates the Liquidator playtest build: a copy of the game's sources in playtest-liquidator/ with PLAYTEST.liquidator on.
// Every hunt there starts at The Liquidator's wave with 11 of the 12 seed words in hand. The copy keeps all its sources inside its
// own folder, as the SDK's game check requires. Re-run after changing the game:
//
//   node games/rarefriend-outlaw/tools/playtest.mjs
//   npx friendsdk dev ./games/rarefriend-outlaw/playtest-liquidator
import { copyFile, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const game = resolve(dirname(fileURLToPath(import.meta.url)), ".."), out = join(game, "playtest-liquidator");
await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });

// The game's own sources and data: the TypeScript files, the stylesheet and game.json (not tools/, practice/ or the docs).
const sources = (await readdir(game, { withFileTypes: true }))
  .filter(entry => entry.isFile() && (/\.(tsx?|css)$/.test(entry.name) || entry.name === "game.json")).map(entry => entry.name);
for (const name of sources) await copyFile(join(game, name), join(out, name));

await writeFile(join(out, "playtest.ts"), `// Generated by tools/playtest.mjs: the Liquidator playtest (do not edit; edit the game and re-run the tool).
export const PLAYTEST = { liquidator: true };
`);
// One folder deeper than the game, so the shared tsconfig and the SDK's type declarations are one level further up.
await writeFile(join(out, "tsconfig.json"), JSON.stringify({
  extends: "../../../tsconfig.json",
  compilerOptions: { rootDir: "../../..", noEmit: true, module: "ESNext", moduleResolution: "Bundler" },
  include: ["**/*.ts", "**/*.tsx", "../../../examples/**/*.d.ts"], exclude: [".friendsdk"],
}, null, 2) + "\n");
await writeFile(join(out, "README.md"), `# Rarefriend Outlaw: Liquidator playtest

Generated by \`tools/playtest.mjs\` from the game's sources; do not edit, re-run the tool after changing the game. It is the real
game with one switch on (\`PLAYTEST.liquidator\`):

- Every hunt starts at **The Liquidator's** wave: the eleven outlaws before him are skipped.
- You start with **11 of the 12 seed words** (all but "tumbleweed"); his wallet can drop the twelfth.

Buy a licence as usual (preview RF), hunt him down, hack his wallet, then settle the licence at the Data Center's Licence
Settlement terminal. Run it from the SDK root:

\`\`\`sh
npx friendsdk dev ./games/rarefriend-outlaw/playtest-liquidator
\`\`\`
`);
console.log(`Liquidator playtest written to ${out} (${sources.length} source files).`);
